name: Scheduled Job

on:
  schedule:
    - cron: "25 10 * * *"

jobs:

  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "This runs every day at 3:55 PM IST"
      - run: date
